### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by stevanspringer** [smilefreak/selectionTools#13]
Hi,

Thanks very much for creating this pipeline! I'm just trying to get started. I'm on OSX and need Fay&Wu's H in particular so I'll be using docker. Unfortunately I'm not able to find your images in the repository.

**$ sudo docker build -t selectiondocker/selectiontools selectionTools/docker/**
sends back
**FATA[0000] stat selectionTools/docker/: no such file or directory**

**$ docker search selectiontools**
finds nothing 

**$ docker search selection**
finds packages by thedutchselection, so it seems docker search is working. 

Thanks very much for your help!

**Comment by murraycadzow** [comment]
Hi,

Great to hear you're interested in our pipeline!
I'm still pretty new to docker so only worked out enough to make a dockerfile to build an image. I haven't committed it to the docker repository so that is why you won't find it there.

My first thought is it could be an issue with where you are running the command from.
my dir structure is:
/home/murray/selectionTools/docker
and I ran the command  sudo docker build -t selectiondocker/selectiontools selectionTools/docker/  from /home/murray/ and it worked for me

Let me know if that resolves the problem

Murray

**Comment by stevanspringer** [comment]
Hi Murray,

That totally makes sense. I thought the command was meant to pull it from the docker repository rather than from a local file. I should have had a look at the directory. It's installing now.

Thanks very much!

Stevan

**Comment by murraycadzow** [comment]
Thanks,
I'll update the documentation to make this clearer


Murray
